version: '3'
services:
  mmslash:
    build: .
    environment:
     - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
    expose:
      - "80"

networks:
  default:
    external:
      name: mattermostdocker_default
