version: '3'
services:
  mmslash:
    build: .
    environment:
     - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
     - POST_WEATHER_TOKEN=${POST_WEATHER_TOKEN}
     - PORT=80
    expose:
      - "80"

networks:
  default:
    external:
      name: mattermostdocker_default
